---
# handlers file for ansible-zabbix-docker
- name: systemctl daemon-reload
  systemd: daemon-reload=yes

- name: restart zbx_postgres
  service: name="zbx_postgres" state=restarted

- name: restart zabbix_server
  service: name="zabbix_server" state=restarted

- name: restart zabbix_web
  service: name="zabbix_web" state=restarted

- name: restart zabbix_agent
  service: name="zabbix_agent" state=restarted


